# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=64, verbose_name='书名')),
                ('book_type', models.CharField(max_length=64, verbose_name='书籍类型')),
                ('book_word_counts', models.IntegerField(verbose_name='字数')),
                ('is_hot_sale', models.BooleanField(verbose_name='是否热售')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
                'db_table': 'book',
            },
        ),
    ]
